name: laravel-swagger-jsons

on:
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create a temp folder
        run: mkdir -p /tmp/packages/arpanext/laravel-swagger-jsons
      - name: Move the package source
        run: mv -v $(ls -A .) /tmp/packages/arpanext/laravel-swagger-jsons
      - name: Create a laravel project
        run: composer create-project laravel/laravel .
      - name: Require laravel-swagger-schemas
        run: composer require arpanext/laravel-swagger-schemas
      - name: Vendor publish for laravel-swagger-schemas
        run: php artisan vendor:publish --provider=Arpanext\\Swagger\\Schemas\\App\\Providers\\AppServiceProvider --tag="swagger-schemas"
      - name: Require laravel-swagger-consoles
        run: composer require arpanext/laravel-swagger-consoles
      - name: Vendor publish for laravel-swagger-schemas
        run: php artisan vendor:publish --provider=Arpanext\\Swagger\\Consoles\\App\\Providers\\AppServiceProvider --tag="swagger-consoles"
      - name: Move the package source
        run: mv -v /tmp/packages .
      - name: Register the package into the composer.json
        run: sed -i '/"require"/i \ \ \ \ "repositories":[{ "type":"path","url":"./packages/arpanext/laravel-swagger-jsons","options":{"symlink":true}}],' ./composer.json
      - name: Dumps the autoloader
        run: composer dumpautoload
      - name: Install the package
        run: composer require arpanext/laravel-swagger-jsons
      - name: Create archive
        run: tar -czvf /tmp/project.tar.gz .
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: /tmp/project.tar.gz
  tests:
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: /tmp
      - name: Extract archive
        run: tar -xzvf /tmp/project.tar.gz
      - name: Run tests
        run: XDEBUG_MODE=coverage vendor/bin/phpunit packages/arpanext/laravel-swagger-jsons --configuration=packages/arpanext/laravel-swagger-jsons/phpunit.xml --coverage-text
      